export { createScene, createGround } from './scene'
export { createCamera } from './camera'
export { createRenderer } from './renderer'
export { createLights } from './lights'
export { createHealthBar, updateHealthBarScale, HEALTH_BAR_WIDTH } from './createHealthBar'
export type { HealthBarMeshes } from './createHealthBar'
